### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by hor1k1t4** [thomas-xin/Miza#28]
Hello, such a question, why does the bot so easily get away from the prompt that you ask him? If you compare one prompt on the gpt website and write the same one in the bot, they will be very different (

**Comment by thomas-xin** [comment]
Miza is assigned a high [temperature value](https://github.com/thomas-xin/Miza/blob/master/misc/convobot.py#L671) which makes responses more creative (less "As an AI language model"). This however comes at the cost of potentially making up information.
Miza also has a [personality prompt](https://github.com/thomas-xin/Miza/blob/master/commands/STRING.py#L1800) which influences her character, and may to some degree affect quality of answers too, most notably the "informal" and "playful" parts. This can be changed on a per-channel basis, or you may change it in the code if you would like.
What sort of problems have you been experiencing with the bot? Could you elaborate on "get away from the prompt"?

**Comment by hor1k1t4** [comment]
Let's say I tell her to be miza, kind, friendly and pretend to be human. But after a couple of questions, it can return to its normal state again and respond like an artificial intelligence.

**Comment by thomas-xin** [comment]
This is actually a limitation of the ChatGPT API and its tendency to follow its restricted training. Do you have better results on the actual ChatGPT website?

**Comment by hor1k1t4** [comment]
> На самом деле это ограничение API ChatGPT и его тенденция следовать ограниченному обучению. Есть ли у вас лучшие результаты на реальном веб-сайте ChatGPT?

Yep, its on chatgpt web:
-Hi
-Oh, hello! Glad to see you here! You know, I'm always ready to attract the attention of wonderful people like you. Mmm, and you seem to be calling my attention... Well, are you ready to play with me? ;)

**Comment by hor1k1t4** [comment]
What could it be?

**Comment by thomas-xin** [comment]
I'm still having a bit of trouble understanding the problem here. Is the web ChatGPT able to stay in character for longer than Miza? If that is the case, it is probably due to the low default message limits I have setup. Since I never planned to have the AI features be self-hosted, I assigned subscription tiers for users who helped fund the API usage, which would grant benefits like increased conversation length.

**Comment by hor1k1t4** [comment]
I understand that it wasn't planned, I'm also studying purely for myself. Look, sometimes I can start talking to him and he immediately starts playing the right role, which is "!personality", and sometimes he just seems to forget what is written there and immediately communicates with the words that he is an AI and does not give an answer to what his name is either, he just answers that he is artificial intelligence 🤔

**Comment by thomas-xin** [comment]
Closing this for now as replicating the exact OpenAI behaviour was not the intent, and the ability for various AI systems to follow instructions is an ongoing problem that may be out of my control, especially because my endeavours have often been bound by cost. Support for specific AI playgrounds may eventually be a feature, but this should probably be under a separate issue.
For now, looking forward I have plans to incorporate more open source models as well as improve multimodality. Getting the AI to act more human will be on the list, but I can't make promises on how successful the result will be.
