### ISSUE TITLE
Feature Request: Regex for `~react`

### ISSUE THREAD

**Issue by FractalGeodes** [thomas-xin/Miza#34]
Title should explain it :monksilly:

Want to be able to overengineer a regular expression for attaching reactions to messages because we're us what else would we do in our spare time :3

**Comment by thomas-xin** [comment]
Hmmm, that can be arranged

Just in case you wanted to know, at the moment the reaction checks for separate words if the trigger is only word characters, otherwise it checks for any occurrence of the substring.

I would assume what you'd want is a third option, where if the set trigger begins with a slash it behaves as a regex instead; this would be fairly easy to implement and regex would be a very powerful algorithm to include here, but the catch is that it potentially allows for poisoned inputs causing infinite loops, which would need to be prevented as that would crash the entire bot without safeguards.

**Comment by thomas-xin** [comment]
For now this will be implemented for regex strings starting and ending with slash (/), and there is a compute time limit of 4 seconds to prevent potential DDoS attacks on Miza. I'll close this issue since it seems to be working, may revisit in the future if ever needed.
